import { readFile, writeFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const css = await readFile(new URL('.build/theme.css', root), 'utf8');
if (/<\/style/i.test(css)) throw new Error('Compiled CSS must not contain a closing style tag.');
const projects = await readFile(new URL('src/partials/project-list.mustache', root), 'utf8');
const themeScript = (await readFile(new URL('src/theme.js', root), 'utf8')).replace(/<\/script/gi, '<\\/script');
const outputs = [];
for (const [filename, marker, replacement] of [
  ['web-header.mustache', '/* THEME_CSS */', css.trim()],
  ['web-feed.mustache', '<!-- PROJECT_LIST -->', projects.trim()],
  ['web-item.mustache', '<!-- PROJECT_LIST -->', projects.trim()],
]) {
  let template = await readFile(new URL(`src/${filename}`, root), 'utf8');
  if (filename === 'web-header.mustache') {
    const scriptMarker = '/* THEME_JS */';
    if (template.split(scriptMarker).length !== 2) {
      throw new Error('src/web-header.mustache must contain exactly one THEME_JS marker.');
    }
    template = template.replace(scriptMarker, () => themeScript.trim());
  }
  if (template.split(marker).length !== 2) {
    throw new Error(`src/${filename} must contain exactly one ${marker} marker.`);
  }
  outputs.push({
    filename,
    destination: new URL(filename, root),
    content: '<!-- Generated by yarn build from src/; do not edit directly. -->\n'
      + template.replace(marker, () => replacement),
  });
}
if (process.argv.includes('--check')) {
  const stale = [];
  for (const {filename, destination, content} of outputs) {
    const existing = await readFile(destination, 'utf8').catch(error => {
      if (error.code === 'ENOENT') return null;
      throw error;
    });
    if (existing !== content) stale.push(filename);
  }
  if (stale.length) throw new Error(`${stale.join(', ')} is stale. Run yarn build and include the generated files.`);
  console.log('Generated theme templates and CSS are up to date.');
} else {
  for (const {destination, content} of outputs) await writeFile(destination, content);
  console.log('Built theme templates with shared projects and compiled Tailwind CSS.');
}
